development:
  adapter: postgresql
  database: olympics_development
  reconnect: false
  pool: 10
  min_messages: WARNING

test:
  adapter: postgresql
  database: olympics_test
  reconnect: false
  pool: 10
  min_messages: WARNING
